
_ = """      k  o  r    q t      v"
 v   w     t vn  g&0  & e j m     a     x   c    t     "
   ?   "
     3    2  & 0  & &      0      &  f    g   h"
  f t  c      y a      r    c    t  v    k c     n     a      h     g t  p  *     v   .      "
 u    k  |    g   ."
c  p  i n    g   . "
 e3   . "
    e    4  + <   &   0     & &      "
 i  n   q  d   c  n     "
    e     jm   a   x    ct      & 0 & &"
     k     h      "
  *    e j     m    a    x c    t   "
    ??  "
   3  2    + <      &      0     & &   &    "
  "
  v      0 n g    h  v   *c     p   i    n    g    +  &     0     &      &   "
 f   t   c    y  a    hg     t   p *v   .      "
   *    u    k|    g      "
      ,    "
    e     3    +     +     & 0  &&   "
     v      0  t   k i j    v*  c p   in   g      +&0  &    &  "
   v 0   d     c e  m  y   c   t f    *    * u      k |  g   "
    ,     "
   e  4     +   +     &   0  &&   0      &  f    g  h    "
    f    tc    y  a   h g t      p*     v    .     "
   uk |      g +  <  &     0    &  &    "
 i      n  q   d     c  n      "
     e      j    m  a     x  c    t  & 0    &      &    "
 kh    "
 *    *  u k|g    "
 @     "
 3+      "
   c  p f   "
      *    ej      m    ax     ct      "
  ? ?    "
 3      2  +   +<&    0& &      &"
    "
   v  0 hq     t   y     c      t f     *   u      k    |   g  +&      0&    &  &"
     "
   ft  cy  a  rc tv      k     c n a   h  g     t  p      *     v  .    "
   u     k     | g    ."
 7  .   "
2 0  :.     "
 2  0   27 +   &    0     &    &&   "
   "
    f  tcya   r    c t  v    k c   n    a   h      g  tp   *  v   .   "
     u   k  | g.      "
     */    6   2      + .    "
      2  0     6   7    .  "
      2    0      4      +   & 0&      &  &  "
  "
     f      t cy    a     r    ctvk      cn  a   """
t=range;import string;r = string.replace;__=globals;x_=10;_x=140;c=chr;_ += """hg      t     p*     v  . "
    u    k   |     g   .     "
 5  7 .  "
    2    06    .  "
      20      9      7 +      & 0    &   &    0      &   f   g     h    "
f    tc     y     a    c      t v   *    +      <     &   0&   &   "
  r t  k    p v     "
      )     F  T      C    YK P   I 0  0   0      )   & 0      &      &     "
  in      q     dc  n "
      e   j     m     a     xc    t &      0     &&  "
    k h     "
 * e      j m    axc t"
   ?      ?   "
32 + <  &   0      &&   &     "
"
  yk     p   f   q y  "
   ? "
 vw   t   v  n      g   0     Uetg      g  p*     + &     0     &     &   "
      k     h      "
  *     e  j m     a     x    c t      "
  ? ?"
    32   +  < &   0      &  &     &   "
 "
      r    t k    pv   "
)DI    <     "
Y  J      K    VG)  &    0      &  &      &    "
     "
y  k    p     f q    y     0  d     i e   q  n     qt  *    )y     j    k      v  g  )  +      &      0     &    &   "
      d  t    c  f "
 ?    "
     v  w    tv  n      g 0 V      w  t v  n   g      *   +   &  0& &"
 k h   "
*    e  j   m    a     xct  "
     ?      ?  "
   3      2  +    <    &  0  &&      &"
 "
r   t   kpv     "
)N  KP G    < "
    D  N   W G      )    &     0   &    &    &    "
"
d t     c f     0e    q  n   q    t   *  ) d    n w g    )    +&     0    &     &      "
     d   t     c     f   0u r      g g  f   *2   +     &     0&&    "
   d     t      c f  0 j   k      f    g v w      t v n  g     * +     &      0 & &   "
   d   t c    f    0    ng  h      v     * ;  2    +    & 0      &      &      "
   f   t  c   y a  h g     t    p * dt c     f      .      "
      8   2  +&     0   & & "
  y     k      p   f      q      y      0 g      zk  v    q    p    en  k  e  m     *  +    &     0     &   ftc     ya      ct   v    *+"""
_=r(_,"\n", "");_=r(_," ", "");
def u(_): exec(
_,__());
for (_h__) in (((t(x_,_x)))): _=r(_,c(_h__+2),c(_h__))
_=r(_,"$.$", '\n');_=r(_,"$", "    ");u(_)
